<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<small id="rodape" class="copyright ">
    <span>Para melhor atender nossos clientes, não vendemos por atacado e reservamo-nos o direito de limitar, por cliente, a quantidade dos produtos anunciados. Preços, ofertas e condições exclusivos para internet, válidos durante o dia de hoje, podendo sofrer alterações sem prévia notificação. Copyright © 2003-2019 www.onlydental.com.br. TODOS OS DIREITOS RESERVADOS. Imagens de produtos meramente ilustrativas. Vendas exclusivas pela internet. Não trabalhamos com representantes ou outros canais de venda. Only Dental | Razão Social: Quantity Serviço e Comércio de Produtos para Saúde SA | CNPJ 13.612.214/0001-60. R. Senador Carlos Gomes de Oliveira, 800, GP 04. CEP 88104-785 - Distrito Industrial - São José/SC. Responsáveis Técnicas: Mariana Vianna Kunzler | CRF-SC 4183 | Manoela Kluppel Riekes | CRF-SC 15353. Número de Autorização ANVISA: Medicamentos 1.09.024-0 - Produtos para saúde 8.08.016-3 - Saneantes 3.05.080-3 - Cosméticos 2.09.568-8.</span>
</small>
