<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php echo $this->getChildHtml("store_language"); ?>
<div class="container">
	<div class="row pb-4">
		<div class="col-8 col-md-6">
            <img src='<?php echo $this->getViewFileUrl('images/logo-hyper-dental-white.png'); ?>' alt="Logo" id="logo-hyper">
		</div>

		<div class="col-4 col-md-6 d-flex justify-content-end align-items-center">

                <img src='<?php echo $this->getViewFileUrl('images/user.svg'); ?>' alt="Login"   id="header-login-user"> 

                <img src='<?php echo $this->getViewFileUrl('images/login.svg'); ?>' alt="Login"  class="mr-5" id="header-login"> 
				
                <img src='<?php echo $this->getViewFileUrl('images/carrinho.svg'); ?>' alt="Carrinho"  id="header-cart" class="ml-4">

                <img src='<?php echo $this->getViewFileUrl('images/menu-mobile.svg'); ?>' alt="Menu Mobile"  id="menu-mobile" class="ml-4">

		</div>
	</div>
	<div class="row">
		<div class="col-md-12 ">
        <ul id="hyper-nav" class="nav nav-justified pt-3">
				<li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#">Uso Contínuo</a>
				</li>
				<li class="nav-item">
                <a class="nav-link dropdown-toggle" href="#">Endodontia</a>
				</li>
                <li class="nav-item">
                <a class="nav-link dropdown-toggle" href="#">Restauração</a>
				</li>
				<li class="nav-item">
                <a class="nav-link dropdown-toggle" href="#">Ortodontia</a>
				</li>
                <li class="nav-item">
                <a class="nav-link dropdown-toggle" href="#">Equipamentos</a>
				</li>
                <li class="nav-item">
                <a class="nav-link dropdown-toggle" href="#">Implantodontia</a>
				</li>
                <li class="nav-item">
                <a class="nav-link dropdown-toggle" href="#">Vestuário</a>
				</li>
                <li class="nav-item">
                <a class="nav-link dropdown-toggle" href="#">Catálogo Virtual</a>
				</li>
			</ul>
            

		</div>
	</div>
	<div class="row">
		<div class="col-md-12">
        <form>
        <div id="search-box" class="input-group" >
            <input  class="form-control py-2 border-right-0 border" type="search"  placeholder="Digite o que você procura">
            
        </div>
</div>
 
  
</form>   
		</div>
	</div>
</div>